### ISSUE TITLE
basic/minimal example

### ISSUE THREAD

**Issue by atornity** [Multirious/bevy_tween#20]
there are so many examples (and they're really cool), it would be nice with a simple "start here" example that just moves a "thing" from A to B or something. This should probably be in the top level examples folder to make it easy to find.

**Comment by Multirious** [comment]
Oh I had just worked on this yesterday. They're not in top level folder but directly in README and module level doc and should be even easier to find 😁

**Comment by PatrickChodowski** [comment]
+1 for the minimal example :) I came here because bevy_tweening seems not to have a simple way to switch animators per entity, but I think its really hard to start with bevy_tween without being overwhelmed.
