### ISSUE TITLE
Implement `Serialize` and `Deserialize`

### ISSUE THREAD

**Issue by janhohenheim** [Multirious/bevy_tween#27]
I'd like `EaseFunction` (and maybe other types?) to implement `Serialize` and `Deserialize` so that I can configure my easings in an external config file. Currently, I have to use [remote derives](https://serde.rs/remote-derive.html) to work around the fact that `bevy_tween` does not export `serde` derives.

**Comment by Multirious** [comment]
Yeah, we can have serde impls.

> bevy_tween does not export serde derives.

I'm not sure what this means though. The crate doesn't even have a dependency on `serde` yet.

**Comment by Multirious** [comment]
> I just realized bevy_reflect derive should've automatically derive Serialize and Deserialize?

That's [`ReflectSerializer`](https://docs.rs/bevy/latest/bevy/reflect/serde/struct.ReflectSerializer.html). Would it work for now?

**Comment by janhohenheim** [comment]
> I'm not sure what this means though. The crate doesn't even have a dependency on serde yet.

Yeah, that's what I meant. Sorry for not being clear 😅

> All types in the crate implements Reflect so we can deserialize and serialize them this way. Would this work?

In theory, but what I'm trying to do is to just register a `GameConfig` struct in [`bevy_common_assets`](https://github.com/NiklasEi/bevy_common_assets), which expects the whole struct to be at least `Deserialize`.

**Comment by Multirious** [comment]
Alright, 7ae79621e296d2074d9bb6fe8863880b1030543e is merged. I've tried to implement Serialize and Deserialize on other types but seems like only `EaseFunction` is the only one that make sense 🤔. I guess I'll be implementing serde on a request basis.

**Comment by janhohenheim** [comment]
Thanks a bunch :D
