### ISSUE TITLE
Consider making `color_lerp` public

### ISSUE THREAD

**Issue by janhohenheim** [Multirious/bevy_tween#34]
If people want to implement their own color interpolators, it would be nice to be able to use the same implementation as the crate uses internally. I left this out of #33 because I wanted your opinion on it first :)

**Comment by Multirious** [comment]
Since the next release would likely be in Bevy 0.14 anyways I decided that I wanted to leave this to the `Mix` trait in the future. And for a while it just felt weird to export one random implementation for specifically color lerp.

**Comment by janhohenheim** [comment]
Ah, that makes sense :)
